### ISSUE TITLE
Symbols missing during debugging

### ISSUE THREAD

**Issue by paaco** [rolandshacks/vs64#14]
I really like your extension to write and debug C64 assembler. However, it appears to miss many symbols in my code.
It appears to only recognize labels starting with '.' on lines with code behind it.
For instance the following code only has '.other:' as label appearing in the debug window:
```
start:  lda .values,x
        sta .other,y
        jmp start
.other:  !byte 1
.values:
  !byte 0
```
It misses the label 'start' because it does not start with a '.'
It also misses the '.values' label because it appears on an empty line.
And note that the recognised label is '.other:' ending with a colon. So you need to type in .other: in the watch window to display it.

As a workaround I look up the address in the .report file. It would be really nice to watch the contents of an address as word value instead of always byte. Just like a label before !word.

**Comment by rosc77** [comment]
Hi. Thanks for the feedback. I'll have a look as soon as possible - unfortunately, I do not really have time these days...

**Comment by paaco** [comment]
@rosc77 Understandable. I forked your code but I'm still figuring out how I should debug the debugger-extension from VS Code. It looks possible to test the parser in `debug_info.js` locally with Node.js though. Would you accept any pull requests?

I did notice that with VS Code 1.42 the file.asm window closes each time during debugging with a notification "file.asm not found". Somehow VS Code cannot find the source file. So I stepped back to 1.41.1 for now. That still works.

**Comment by rosc77** [comment]
Hi, thanks for taking the initiative. I am totally fine handing over and accepting PRs.

 

Cheers!

Roland

 

Von: paaco <notifications@github.com> 
Gesendet: Dienstag, 18. Februar 2020 10:05
An: rosc77/vs64 <vs64@noreply.github.com>
Cc: Roland <roland.schabenberger@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [rosc77/vs64] Symbols missing during debugging (#14)

 

@rosc77 <https://github.com/rosc77>  Understandable. I forked your code but I'm still figuring out how I should debug the debugger-extension from VS Code. It looks possible to test the parser in debug_info.js locally with Node.js though. Would you accept any pull requests?

I did notice that with VS Code 1.42 the file.asm window closes each time during debugging with a notification "file.asm not found". Somehow VS Code cannot find the source file. So I stepped back to 1.41.1 for now. That still works.

**Comment by paaco** [comment]
@rosc77 Thanks for publishing a new version (I assume this is a manual action from your side). However, I've made a mistake and the resulting 0.11 package does not work because its missing the dependencies. My bad, I should have tested the generated package locally. I'll make a PR for it the coming days.

**Comment by paaco** [comment]
@rosc77 Added PR #18.
