### ISSUE TITLE
Code formatter addition?

### ISSUE THREAD

**Issue by Gtach** [rolandshacks/vs64#34]
Hi,
I'm using your extension and it works great.

I'm facing 12000 lines of code converted from an obscure C64 assembler from 1984, made by a friend of a friend back then. 
It all builds, but the code layout needs improvement. When reaching line 500 hand formatting I tried an asm formatter with dubious results.
Would you consider adding a, somewhat configurable, formatter to the extension?

Just asking, but would be great. :-)

Regards and thanks for the great work!

**Comment by rolandshacks** [comment]
Hi,

Thanks for the feedback - let me think about it (and see when I could find
some time...). Challenge is to write a parser for assembler syntaxes which
I carefully avoided so far...

Best regards,
Roland

PS. If you like the extension, it would be great to give some positive
feedback on the vscode marketplace.



Am Di., 28. März 2023 um 16:38 Uhr schrieb Gtach ***@***.***>:

**Comment by rolandshacks** [comment]
Should be fixed with [v2.1.3](https://github.com/rolandshacks/vs64/releases/tag/v2.1.3) which is on the [marketplace](https://marketplace.visualstudio.com/items?itemName=rosc.vs64) now. You should get the auto-update.
