### ISSUE TITLE
.ninja_log not deleted on new build

### ISSUE THREAD

**Issue by Gtach** [rolandshacks/vs64#35]
Hi,
I'm experiencing a funny issue.
A build went file, creating the artefacts including .ninja_log.
I then make changes, and on save a new compile starts, saying all fine 'ninja: no work to do'.
But it had not built, not showing the errors.
When I then delete .ninja_log manually it builds again, until success, then creating a new  .ninja_log and the problem repeats.
Something wrong or user error?

Regards and thanks

**Comment by rolandshacks** [comment]
Hi,

In case you're using several source modules, could you try adding all source files to the "sources" list at the project file? Alternatively, it would be great to get a "failing example" to reproduce your setup.

Regards,
Roland

**Comment by Gtach** [comment]
Yes, several .asm files. I’ll try that and come back tomorrow.
Thanks for the fast answer.

**Comment by rolandshacks** [comment]
Bug should be fixed with version [v2.1.3](https://github.com/rolandshacks/vs64/releases/tag/v2.1.3).

It is on the vscode [marketplace](https://marketplace.visualstudio.com/items?itemName=rosc.vs64) and you should get auto-updated whenever you restart vscode.

Please let me know if this solves your issues.

Thanks.

**Comment by Gtach** [comment]
It updated fine, but...
'failed to spawn process '/home/rh/.vscode/extensions/rosc.vs64-2.1.3/resources/ninja/linux/ninja: EACCES'

**Comment by rolandshacks** [comment]
I built the extension now on linux, maybe you could try v2.1.4.
My guess is that on windows, the exe flags for the ninja executables are getting lost. Damn.

**Comment by rolandshacks** [comment]
Good!
Yes, adding the asm sources doesn't make sense if they're included files - and leads to build failures. Just keep them out of the project file and leave it to vs64 to scan and auto-detect the dependencies.

**Comment by rolandshacks** [comment]
In case you're planning to open-source your project - let me know once it's public. I'd be happy for more test projects...

**Comment by rolandshacks** [comment]
Hey, this is great. More than happy to support you with features "just-in-time" as my schedule allows. And you're right, German is indeed no problem. Feel free to reach out via PM!

**Comment by rolandshacks** [comment]
Also, for tooling - what would you think are important ones? Not sure if I would overload and over-engineer vs64, but maybe there could be a few little things (at least, I could try to open up the build kit for custom tooling).
