### ISSUE TITLE
vice not launching or attaching on debug sessions

### ISSUE THREAD

**Issue by Gtach** [rolandshacks/vs64#36]
Hi,
title says it all.
launch.config has the three settings, but nothing happens.
vice is installed and I can launch it manually, though.
This is on Ubuntu 22.10.

Regards

**Comment by rolandshacks** [comment]
Could you please turn on verbose outputs to get more debugging information in the VS64 settings?

**Comment by rolandshacks** [comment]
Just one quick question: you selected the "Vice" launch configuration - and not the 6502 emulator? That would be the simplest explanation... (just had to ask as not everyone is super familiar with vscode).

**Comment by Gtach** [comment]
Yes, I selected "launch vice", I have three configurations in the file.
I enabled trace logging but could not find the log file. Where is it written to?
On another note, I'm working in parallel on a desktop and laptop machine, both on Ubuntu 22.10.
The laptop starts vice fine when debugging. The problem is the main machine.

**Comment by rolandshacks** [comment]
Both environments do have the most recent version of vice installed?

**Comment by Gtach** [comment]
I did install 2.1.5, thanks for the effort.

About similar setup. As far as I know it's similar. Same Ubuntu version, vice installed via apt. But obviously something must be different.

And about the tooling :-) It's a long shot and no hurry, but the extended plan is to make a version for the 'Commander X16'. https://www.commanderx16.com/
Would be nice to support the emulator at a point in the future. :-)

Else the extensions works great. It is such a relief to use modern tools developing C64 software instead of doing it all ON the C64. First time I started debugging directly on vice I nearly shed a tear... :-) And all the supporting tools are made in C#.

 Log now shows...

[Extension Host]  24.448 extension.js:495 T/Extension.Extension.showStatus: status: $(pass) Build succeeded
console.ts:137 [Extension Host]  24.497 debug_session.js:98 D/DebugSession.DebugSession.start: start debug session
console.ts:137 [Extension Host]  24.520 debug_session.js:342 T/DebugSession.DebugSession.launchRequest: launchRequest
console.ts:137 [Extension Host]  24.521 connector.js:1061 D/ViceConnector.ViceProcess.spawn: launch emulator: x64sc -binarymonitor -autostartprgmode 1
console.ts:137 [Extension Host]  24.531 connector.js:295 T/ViceConnector.Socket.connectErrorEventListener: peer not ready when trying to connect: Error: connect ECONNREFUSED 127.0.0.1:6502
console.ts:137 [Extension Host]  24.594 connector.js:1042 D/ViceConnector.ViceProcess.stderr: x64sc: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
console.ts:137 [Extension Host]  24.781 connector.js:295 T/ViceConnector.Socket.connectErrorEventListener: peer not ready when trying to connect: Error: connect ECONNREFUSED 127.0.0.1:6502

goes on with the same output, and then...

[Extension Host]  29.539 debug_session.js:283 E/DebugSession.DebugSession.createEmulatorInstance: debug error: failed to connect to emulator process

**Comment by rolandshacks** [comment]
Could it be that the port 6502 is used by another instance?

**Comment by rolandshacks** [comment]
Or, maybe you could check the vice settings for the "binary monitor". Look if the port is indeed 6502.

**Comment by Gtach** [comment]
The setting is on 6502 (I see what you did there, vice...)
The monitor settings are the same on the working and not working machine.
The port is not in use, as far a I can see (sudo lsof -i -P -n | grep LISTEN)

What is this in the logs...
undefined symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

**Comment by rolandshacks** [comment]
hmm, pthreads lib ... does it even start if you directly do "x64sc -binarymonitor -autostartprgmode 1" on the terminal?

**Comment by rolandshacks** [comment]
Maybe there is an issue with vscode... found this: https://github.com/microsoft/vscode/issues/179274

**Comment by Gtach** [comment]
Yes, issue is with recent ubuntu update and vs code snap.
I uninstalled the snap, downloaded the .deb and reinstalled it. 
Works...
Noice!

Thanks

**Comment by rolandshacks** [comment]
Glad we found it. Thanks for giving all the feedback and assistance!
