### ISSUE TITLE
Add more build targets or 'post build' task

### ISSUE THREAD

**Issue by Gtach** [rolandshacks/vs64#38]
I would like to copy the build result prg file to another folder after a successful build.
Can this be configured in the Ninja system or maybe in a VS Code task?
I could not find a good clue myself.

Thanks

**Comment by rolandshacks** [comment]
Maybe this could be a good workaround for now:

- https://code.visualstudio.com/docs/editor/tasks#_compound-tasks
- https://stackoverflow.com/questions/52238171/how-to-run-multiple-tasks-in-vs-code-on-build

**Comment by Gtach** [comment]
Ah, yes, I figured out how to add a dependent task. That works, nice, thanks.

A small snag is, that VS64 specifically starts the task of type "vs64" when building automatically, not the one having the kind build and the 'isDefault=true' flag set.
I still need to remember to press 'ctrl-shift-b' to start the default build task when done.  :-)

I don't care it will copy on every build, the whole process is lightning fast anyway. Compiles 12000 lines in a second...

**Comment by rolandshacks** [comment]
Exactly. These days, producing 64K binaries sounds like a joke...
Maybe I will find some time soon to look at the build flow. For now, I am finalizing the first version of an integrated resource compiler (translating anything to C++/C/ASM source - SID files, sprites from SpritePad or SpiteMate and character sets/tiles/maps from CharPad. It feels really great and gives an amazing speedup to the workflow...
Let me know if you're interested, will release a first beta soon on github.

**Comment by Gtach** [comment]
Definetly. After I get the game compiling and running just extracting the existing assets from the 1988 binaries I will need a workflow for all the grafics. We used sprites and fonts for tiles, too. Then all the specialised tools for the npcs, shops, riddles and more… And then the master tool to distribute it all on the four floppy disks. Most of it is sector based, not file based. We had our own 1541 communicaion setup that worked without needing to halt interrupts. With that one could walk ‘seemlessly’ over the 160k main map, disk loading in the background wtih two raster interrupts running to handle three font sets and 24 sprites…

**Comment by rolandshacks** [comment]
Maybe relevant: I just released the first version of VS64 coming with a resource compiler: 
https://github.com/rolandshacks/vs64/releases/tag/v2.2.0

Support for SpritePad/Pro, SpriteMate, CharPad/Pro and the usual SID files. Maybe worth having a look.

**Comment by rolandshacks** [comment]
Not directly related to this issue - but all former releases are now published on the marketplace with v2.3.4. Also included: resource compilation for PCM waveforms.... fun to play with SID sample playback... super easy to do. 
(https://github.com/rolandshacks/c64hacks/tree/main/variants/asm shows how to use!)
