### ISSUE TITLE
VS Code and Go To functionality

### ISSUE THREAD

**Issue by Gtach** [rolandshacks/vs64#39]
Hi,
I'm still working on my project using VS64 and it works very satisfying.
You remember the 15000 lines of assembly code I'm dealing with? I've ripped them apart into about 50 (and growing) seperate files, adding scopes and refactoring label and subroutine names. All works fine and the debugging features are a livesaver. Great.

I'm happy as it is, but obviously there can be more. :-)
I noticed none of VS Codes GoTo functions seem to do anything. Say, GoTo definition of a label, or GoTo references.

With a project of the scope I'm dealing with that would be a great help. I can find my way around with Find and other means, but it would be nice to hop around the code files with hokeys and mentioned GoTo functions.

Am I missing something or does this needed to be supported by VS64 in sme way?

Regards Rüdiger

**Comment by rolandshacks** [comment]
Hi Rüdiger,
Thanks for the feedback. Let me look into how the goto requests are handled. I must admit that for a while, I was rather focused on LLVM and might have missed some of the options I could offer based on the generated ACME debug and label infos.
Cheers.

**Comment by rolandshacks** [comment]
Implemented in version 2.3.0.

Please download the latest vsix and manually install to test: https://github.com/rolandshacks/vs64/releases/latest

**Comment by Gtach** [comment]
Wow, cool, works!

Go to references works like a charm.
Go to definition finds labels as abc=123 , but not subroutines as in 'JSR FooBar' or labels as 'LDA PlayerVector,x', where PlayerVector is defined as e.g. 'PlayerVector !word Left, Right, Up, Down'

The go to references looks decidedly cool. :-)

Thanks a lot.

Btw, looks like you're spending as much time outside in the sunshine as me... close to zero :-)

**Comment by rolandshacks** [comment]
I patched it. Please manually upgrade to 2.3.1 : https://github.com/rolandshacks/vs64/releases/latest

PS. It was my last week of rainy vacation... I guess from now on, my time for vs64 will be slightly reduced... and the weather will hopefully get better soon :-)
