### ISSUE TITLE
VICE not launching or attaching on debug

### ISSUE THREAD

**Issue by torokze** [rolandshacks/vs64#40]
Hi,

I have this debugger issue with VICE 3.7-win64. Neither attach nor launch works.
The internal debugger works just fine. The VICE works. There are no multiple instances at the same time.
I'm using Windows 11, VSCode 1.77.3, VS64 2.2.1

[attach.vscode-app-1682831715579.log](https://github.com/rolandshacks/vs64/files/11360630/attach.vscode-app-1682831715579.log)
[launch.vscode-app-1682831806691.log](https://github.com/rolandshacks/vs64/files/11360631/launch.vscode-app-1682831806691.log)
[vice.log](https://github.com/rolandshacks/vs64/files/11360632/vice.log)

**Comment by rolandshacks** [comment]
You could try the following:
- manually launch vice
- make sure the "Binary Remote Monitor" is enabled on port 6502
- make sure the "Remote Monitor" is NOT using port 6502
- now "attach" your program to vice (using port 6502)
Does that connect and work? If yes, save your settings and try the automated way again.

**Comment by torokze** [comment]
I've tried these:
- x64sc.exe -binarymonitor -binarymonitoraddress ip4://127.0.0.1:6502 -autostartprgmode 1 -remotemonitoraddress ip4://127.0.0.1:6510
- x64sc.exe -binarymonitor -binarymonitoraddress ip4://127.0.0.1:6502 -autostartprgmode 1 +remotemonitor

launch.json entry:
        ```{
            "type": "vice",
            "request": "attach",
            "name": "Attach Vice",
            "hostname": "localhost",
            "port": 6502,
            "preLaunchTask": "${defaultBuildTask}"
        }```

The emulator starts but as soon as I hit F5 (attach vice) it quits in both cases.

**Comment by rolandshacks** [comment]
Let me try to reproduce it precisely... Which version and variant of VICE are you using?

- [VICE 3.7](https://sourceforge.net/projects/vice-emu/files/releases/binaries/windows/GTK3VICE-3.7-win64.zip/download) (64bit GTK3)
- or [VICE 3.7](https://sourceforge.net/projects/vice-emu/files/releases/binaries/windows/SDL2VICE-3.7-win64.zip/download) (64bit SDL2)

**Comment by rolandshacks** [comment]
"Quits in both cases" means: the debugging session stops / detaches unexpectedly, but the VICE process keeps going?

**Comment by rolandshacks** [comment]
This, for example, is the 64bit GTK version working smoothly on Win11. (SDL-VICE works exactly the same way...)

![grafik](https://user-images.githubusercontent.com/1459248/235344638-7bf8b9c2-f0d2-4300-9500-19b9093a6ad3.png)

Another Idea: When installing VICE on Windows, there's the antivirus trying to shield your computer. Could you try to manually start to see if VICE is working as expected?

**Comment by rolandshacks** [comment]
Another Idea: When installing VICE on Windows, there's the antivirus trying to **shield your computer**. Could you try to manually start to see if VICE is working as expected?

**Comment by torokze** [comment]
VICE 3.7 SDL
The vice process quits completely.
I'll try the GTK version ASAP.

**Comment by torokze** [comment]
The GTK version works as expected. Thanks.

**Comment by rolandshacks** [comment]
Hmmm. I'll check with the SDL version later today!

**Comment by rolandshacks** [comment]
I can reproduce the VICE-SDL crash on windows, but cannot explain. The only thing I could improve was the handling of the crash and the resulting ECONNRESET socket failure.

**Comment by rolandshacks** [comment]
Btw. it works seamlessly on Linux x64 with the SDL version of VICE. Seems to be a Win64/SDL/VICE bug.
