### ISSUE TITLE
"args" ignored, trying to add a custom cc65 system config

### ISSUE THREAD

**Issue by bastetfurry** [rolandshacks/vs64#42]
Trying to add a custom system config, ie. "c64.cfg", to my project inside the project-config.json's args list and, well, the args won't get added to the ld65 call.

I am importing an older project to test the extension, so don't mind the year.

```
{
    "name": "Partygames",
    "description": "Partygames for Bunkerparty 2017",
    "toolkit": "cc65",
    "sources": [
        "src/main.c",
        "src/asteroidrun.c",
        "src/supplyrun.c",
        "src/helper.c",
        "src/charset.s",
        "src/irq.s"
    ],
    "build": "debug",
    "definitions": [],
    "includes": [
    ],
    "args": ["-C c64.cfg"],
    "compiler": ""
}
```

**Comment by rolandshacks** [comment]
I need to check, you intend to set a linker config file, correct?

**Comment by rolandshacks** [comment]
Found it. It's both a bug and a bit of missing functionality.

Next release will fix it and add the following config parameters:

- "assemblerFlags": "arg arg arg",
- "compilerFlags": "arg arg arg",
- "linkerFlags": "arg arg arg"

**Comment by rolandshacks** [comment]
Please download and manually install the new release: https://github.com/rolandshacks/vs64/releases
Thanks for reporting!

**Comment by bastetfurry** [comment]
Thanks for fixing this, will do tomorrow as today is a holiday over here and i am with family. :)
