### ISSUE TITLE
Change resource compiler options to generate c

### ISSUE THREAD

**Issue by tomaz** [rolandshacks/vs64#44]
Heya! Is it possible to change default `rc.py` to use `--cc` instead of `--cpp`? Using `llvm-mos` configuration if that matters...

Tried with `"resources": "--cc"` in `project-config.json` but it doesn't change anything. Judging from [source code](https://github.com/rolandshacks/vs64/blob/17683f56aeffb049de114ef1520a134adc80a400/src/project/project.js#L1283) this seems to be hard coded?

**Comment by rolandshacks** [comment]
Thanks for the feedback.
Will have a look - next version is around the corner anyways. Good time to ask!

**Comment by rolandshacks** [comment]
Hi. 

Latest release v2.4.1 of vs64 now provides that option.

https://github.com/rolandshacks/vs64/releases

Please notice that you have to manually download install the .vsix as it is not yet published on the vscode marketplace.

**Comment by tomaz** [comment]
Wow that was fast, thanks!

I tested it, works - parameters are accepted, but `rc.py` still generates `.cpp` file (also `.o`). Also then linker fails for not finding the symbols declared in that file, though the cpp content is correct.

Cmd line without `rcFlags`:
```
c:\...\.vscode\extensions\rosc.vs64-2.4.1\resources\python\python.exe 
   c:\...\.vscode\extensions\rosc.vs64-2.4.1\tools\rc.py 
   --config c:\Projects\Test\project-config.json 
   --format cpp 
   -o c:\Projects\Test
```

Cmd line with `"rcFlags": "--format cc"`
```
c:\...\.vscode\extensions\rosc.vs64-2.4.1\resources\python\python.exe 
   c:\...\.vscode\extensions\rosc.vs64-2.4.1\tools\rc.py 
   --format cc 
   --config c:\Projects\Test\project-config.json 
   -o c:\Projects\Test
```

I manually put pars into separate lines in both cases for better readability...

maybe I'm missing something?

**Comment by tomaz** [comment]
Maybe it's because project is configured as c++ 🤔 I didn't find a way to set it up as c though...

**Comment by rolandshacks** [comment]
I think you don't miss anything, my change was not fixing everything
100%... just I didn't have more time :-)

Work on the resource compiler is planned anyways for better audio signal
processing, maybe I'll find a smart way to fix the extensions also...

Cheers!
Roland

Am Mo., 3. Juli 2023 um 10:35 Uhr schrieb tomaz ***@***.***>:

**Comment by rolandshacks** [comment]
Release v.2.4.2 is out (to be manually installed from github). Please have a look: https://github.com/rolandshacks/vs64/releases
