### ISSUE TITLE
Export resource colors for sprites and characters

### ISSUE THREAD

**Issue by tomaz** [rolandshacks/vs64#45]
As far as I can see `rc.py` only exports colors in comments (only tested with CharPadPro and SpritePadPro, but also don't see this option in source code). Or maybe I'm missing something?

KickAssembler output from CharPadPro:
```
////////////////////////////////////////////////////////////////////////////////
// Type:         CharPad Data (Pro Version, Format 8)
// Editor:       https://subchristsoftware.itch.io/charpad-c64-pro
// Characters:   68
// Size:         544 bytes
// Palette:      {7, 8, 9, 12}
// Display Mode: Text Multi-Color
////////////////////////////////////////////////////////////////////////////////
```

KickAssembler output from SpritePadPro:
```
////////////////////////////////////////////////////////////////////////////////
// Type:         SpritePad Data (Pro Version, Format 5)
// Editor:       https://subchristsoftware.itch.io/spritepad-c64-pro
// Name:         sprite0
// Palette:      {0, 1, 0} (screen, multicolor 1, multicolor 2)
// Color:        1
// Multicolor:   True
// Double X:     False
// Double Y:     False
// Overlay:      False
// Flags:        %10000001 (MYXOCCCC: stored in data byte 64)
////////////////////////////////////////////////////////////////////////////////
```

**Comment by rolandshacks** [comment]
Thanks for reminding me of this. It was left out intentionally, but should be added now.
I'll put it to my list of features to be implemented soon.

**Comment by tomaz** [comment]
Do you accept pull requests if I get the time and take a look?

**Comment by tomaz** [comment]
Actually went ahead and prepared PR, it was a simple addition. But please comment if you have any reservations, want different formatting, etc. - I'm completely unfamiliar with Python, so there are very likely better ways to solve it...
