### ISSUE TITLE
Fail To Build New Project

### ISSUE THREAD

**Issue by c64manguy** [rolandshacks/vs64#48]
I keep getting a failure when I try to build a new project... I have attached the output. Do you know what I am missing?

FAILED: c:/Users/harmo/Documents/Retro Computers/C64/Assembly Files/build/VS64_TEST.prg c:/Users/harmo/Documents/Retro Computers/C64/Assembly Files/build/VS64_TEST.report 
C:\Users\harmo\Documents\Retro Computers\C64\acme0.97mac\acme.exe --msvc --maxerrors 99 -DDEBUG=1 -f cbm --cpu 6510 -I "c:\Users\harmo\Documents\Retro Computers\C64\Assembly Files" -I "c:\Users\harmo\Documents\Retro Computers\C64\Assembly Files\build" -r "c:\Users\harmo\Documents\Retro Computers\C64\Assembly Files\build\VS64_TEST.report" 
-o "c:\Users\harmo\Documents\Retro Computers\C64\Assembly Files\build\VS64_TEST.prg" "c:\Users\harmo\Documents\Retro Computers\C64\Assembly Files\src\main.asm"
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

**Comment by rolandshacks** [comment]
Hi. Seems like your ACME installation (acme.exe) is not getting found. Are you sure paths and installation are valid?

**Comment by c64manguy** [comment]
Thanks for the quick reply! If it is supposed to have ACME.exe I think that may be the problem. The acme I downloaded has a file called "acme" with no file type. I'm guessing that is exactly the issue. I will see what I can figure out.

**Comment by c64manguy** [comment]
I had the Mac version. I was able to find the Win version on the internet but not very easily. The sourceforge link only has mac from what I could tell.
