### ISSUE TITLE
build succeeded Error: read ECONNRESET

### ISSUE THREAD

**Issue by c64manguy** [rolandshacks/vs64#49]
Im sorry for being a pest but I got the application working but now I get the message below and the vice emulator opens and then immediately closes. Any idea what I'm doing wrong with this one?

build succeeded
Error: read ECONNRESET

**Comment by rolandshacks** [comment]
This can be due to a known issue with the SDL version of the Vice emulator on windows. Please try using the GTK build instead.

**Comment by c64manguy** [comment]
Ok. I'll give it a shot. Thanks again!

**Comment by rolandshacks** [comment]
Hi. Is there any update on this? I assume it indeed was the vice bug (which has already been reported).
