### ISSUE TITLE
Rewrite issue in the build.ninja file

### ISSUE THREAD

**Issue by Gtach** [rolandshacks/vs64#51]
Hi,
after a little timeout I'm back on the project. VS64 works fine, but I'm experiencing a weird issue with the flags line in the build.ninja file.

My project consist of several asm projects. Some need to be compiled with -f cbm, some with -f plain. 
I change it directly in the build.ninja file, but it gets set back at some point.

Do I need to configure this another place? I see in the documentation you can 'add' flags, but what with the ones in the line alreay?

Thanks

**Comment by rolandshacks** [comment]
Hi. 

The "build.ninja" file - as all the other files in the build folder are all auto-generated. Please never edit them directly as they''re getting overwritten every time there's a relevant change.

**Comment by Gtach** [comment]
Allright, got it.
If you add 
    "args": [
        "-f", "plain"
    ],
to the project-config.json it will replace the standard -f cbm with it.
Good, was not completely clear in the documentation.

Thanks
