### ISSUE TITLE
Extension not installable VSCodium

### ISSUE THREAD

**Issue by TheCount** [rolandshacks/vs64#54]
* The extension does not show up under `Extensions`.
* Downloading the extension from the marketplace and installing manually yields the following error message: `Unable to install extension 'rosc.vs64' as it is not compatible with VSCodium '1.84.2'.`
* Checking out this repo and building the extension manually works, but trying to install it yields the same error message.

The problem might be that I use the telemetry-free version of VSCode (see https://vscodium.com/). However, all other extensions I use have so far been available under `Extensions`, or at least manually installable.

**Comment by TheCount** [comment]
Never mind. It works with `v2.5.2` but not `v2.5.3`. Probably the VSCodium build is just too old. Sorry for the noise.

**Comment by rolandshacks** [comment]
Hi Alexander. Thanks for testing on VSCodium! It was on my list of things to do...
Good to hear it's basically working.
