### ISSUE TITLE
Release 2.5.3 on Raspberry Pi OS. Ninja Build Problem

### ISSUE THREAD

**Issue by AndyJBuchanan** [rolandshacks/vs64#58]
When I installed the extension my Rapsberry Pi 5 and tried the sample work spaces I was getting a build error from ninja:

**/home/ajb/.vscode/extensions/rosc.vs64-2.5.3/resources/ninja/linux/ninja: 1: Syntax error: "(" unexpected
failed with exit code 2**

I was able to hack around this for now by installing a current **ninja-build** package and replacing the **resources/ninja/linux/ninja**
executable in my installed extension. 
 
$ apt list ninja-build --installed
ninja-build/stable,now 1.11.1-1 arm64 [installed]

$ cat /proc/version
Linux version 6.6.20+rpt-rpi-2712 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07)

**Comment by AndyJBuchanan** [comment]
And now I've just spotted the setting to configure an ninja path. Doh!

**Comment by rolandshacks** [comment]
I think arm64 isn't handled - but you're right, setting the path is the way to go for now.

**Comment by AndyJBuchanan** [comment]
Can confirm setting the path works fine. Thanks.
